from gi.repository import Gdk
screen = Gdk.Screen.get_default()
SCREEN_WIDTH = screen.get_width()
SCREEN_HEIGHT = screen.get_height()

BOARD_LINES = int(SCREEN_HEIGHT * 0.04)
BOARD_COLUMNS = int(SCREEN_WIDTH * 0.04)
BOARD_UNITY_WIDTH = SCREEN_WIDTH / BOARD_COLUMNS
BOARD_UNITY_HEIGHT = SCREEN_HEIGHT / BOARD_LINES
BOARD_UNITY_CENTER_X = BOARD_UNITY_WIDTH / 2
BOARD_UNITY_CENTER_Y = BOARD_UNITY_HEIGHT / 2
WALLS = min(BOARD_LINES, BOARD_COLUMNS)
WALL_SIZE = min(BOARD_LINES / 5, BOARD_COLUMNS / 5)
